import Check from "../../../../helpers/validation/check.js";
import { job_opening } from "../../../master/models/job_opening.js";
import { riwayat_apply } from "../../models/riwayat_apply.js";

export const create = async ({
  id_job_opening,
  id_user,
  no_ktp,
  nama_lengkap,
  tempat_lahir,
  tanggal_lahir,
  jenis_kelamin,
  golongan_darah,
  alamat_ktp,
  alamat_ktp_id_provinsi,
  alamat_ktp_provinsi,
  alamat_ktp_id_kota,
  alamat_ktp_kota,
  alamat_ktp_id_kecamatan,
  alamat_ktp_kecamatan,
  alamat_ktp_id_kelurahan,
  alamat_ktp_kelurahan,
  alamat_domisili,
  alamat_domisili_id_provinsi,
  alamat_domisili_provinsi,
  alamat_domisili_id_kota,
  alamat_domisili_kota,
  alamat_domisili_id_kecamatan,
  alamat_domisili_kecamatan,
  alamat_domisili_id_kelurahan,
  alamat_domisili_kelurahan,
  no_telpon,
  nama_kontak_darurat,
  nomor_kontak_darurat,
  riwayat_pekerjaan,
  riwayat_pendidikan,
  riwayat_pelatihan,
  is_relocation,
  expected_salary,
  agama,
  status,
}) => {
  try {
    console.log({
      id_job_opening,
      id_user,
      no_ktp,
      nama_lengkap,
      tempat_lahir,
      tanggal_lahir,
      jenis_kelamin,
      golongan_darah,
      alamat_ktp,
      alamat_ktp_id_provinsi,
      alamat_ktp_provinsi,
      alamat_ktp_id_kota,
      alamat_ktp_kota,
      alamat_ktp_id_kecamatan,
      alamat_ktp_kecamatan,
      alamat_ktp_id_kelurahan,
      alamat_ktp_kelurahan,
      alamat_domisili,
      alamat_domisili_id_provinsi,
      alamat_domisili_provinsi,
      alamat_domisili_id_kota,
      alamat_domisili_kota,
      alamat_domisili_id_kecamatan,
      alamat_domisili_kecamatan,
      alamat_domisili_id_kelurahan,
      alamat_domisili_kelurahan,
      no_telpon,
      nama_kontak_darurat,
      nomor_kontak_darurat,
      riwayat_pekerjaan,
      riwayat_pendidikan,
      riwayat_pelatihan,
      is_relocation,
      expected_salary,
      agama,
      status,
    });
    const job = await job_opening.findByPk(id_job_opening);
    Check.checkExistenceOrThrow(job, "job");
    // Membuat entri baru menggunakan parameter yang diterima
    const result = await riwayat_apply.create({
      id_job_opening,
      id_user,
      no_ktp,
      nama_lengkap,
      tempat_lahir,
      tanggal_lahir,
      jenis_kelamin,
      golongan_darah,
      alamat_ktp,
      alamat_ktp_id_provinsi,
      alamat_ktp_provinsi,
      alamat_ktp_id_kota,
      alamat_ktp_kota,
      alamat_ktp_id_kecamatan,
      alamat_ktp_kecamatan,
      alamat_ktp_id_kelurahan,
      alamat_ktp_kelurahan,
      alamat_domisili,
      alamat_domisili_id_provinsi,
      alamat_domisili_provinsi,
      alamat_domisili_id_kota,
      alamat_domisili_kota,
      alamat_domisili_id_kecamatan,
      alamat_domisili_kecamatan,
      alamat_domisili_id_kelurahan,
      alamat_domisili_kelurahan,
      no_telpon,
      nama_kontak_darurat,
      nomor_kontak_darurat,
      riwayat_pekerjaan,
      riwayat_pendidikan,
      riwayat_pelatihan,
      is_relocation,
      expected_salary,
      agama,
      status,
    });

    return result;
  } catch (error) {
    throw error;
  }
};
